services:
  db:
    image: mysql:latest
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=roottoor
      - MYSQL_DATABASE=banana
      - MYSQL_USER=banana
      - MYSQL_PASSWORD=flakes
    ports:
      - "3306:3306"
    volumes:
      - "./sql_scripts/schema.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./sql_scripts/data.sql:/docker-entrypoint-initdb.d/2.sql"
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  
  api:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "5001:8081"
    links:
      - db:db